version: '3'
services:
  #db:
  #  image: postgres
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "foreman start -f Procfile.dev-server"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    #environment:
    #  DATABASE_URL: postgres://postgres@db
    #depends_on:
    #  - db