subscriptions:
  plans:
    - 
      name: "free"
      id: 618560
      features:
        -
          name: Segments
          active: true
          count: unlimited
        -
          name: Leads
          active: true
          count: unlimited
        -
          name: AppUsers
          active: true
          count: unlimited
        - 
          name: Conversations
          active: true
          count: unlimited

        - 
          name: BotTasks
          active: false
          count: unlimited
        - 
          name: Integrations
          active: true
          count: unlimited

        - 
          name: Campaigns
          active: false
          count: unlimited

        - 
          name: Tours
          active: false
          count: unlimited

        - 
          name: UserAutoMessages
          active: false
          count: unlimited

        - name: OutgoingWebhooks
          active: false
          count: unlimited

        - name: OauthApplications
          active: true
          count: unlimited
          
        - name: Articles
          active: false
          count: unlimited

        - name: QuickReplies
          active: true
          count: unlimited

        - name: CustomAttributes
          active: false
          count: unlimited

    - 
      name: "rookie"
      id: 616249
      features:
        -
          name: Segments
          active: true
          count: unlimited
        -
          name: Leads
          active: true
          count: unlimited
        -
          name: AppUsers
          active: true
          count: unlimited
        - 
          name: Conversations
          active: true
          count: unlimited
        - 
          name: BotTasks
          active: false
          count: unlimited
        - 
          name: Integrations
          active: true
          count: unlimited
        - 
          name: Campaigns
          active: false
          count: unlimited
        - 
          name: Tours
          active: false
          count: unlimited
        - 
          name: UserAutoMessages
          active: false
          count: unlimited
        - 
          name: OutgoingWebhooks
          active: true
          count: unlimited
        - 
          name: OauthApplications
          active: true
          count: unlimited
        - 
          name: Articles
          active: true
          count: unlimited
        - 
          name: QuickReplies
          active: true
          count: unlimited
        - 
          name: CustomAttributes
          active: false
          count: unlimited
    
    - 
      name: "super"
      id: 596123
      features:
        -
          name: Segments
          active: true
          count: unlimited
        -
          name: Leads
          active: true
          count: unlimited
        -
          name: AppUsers
          active: true
          count: unlimited
        - 
          name: Conversations
          active: true
          count: unlimited
        - 
          name: BotTasks
          active: true
          count: unlimited
        - 
          name: Integrations
          active: true
          count: unlimited
        - 
          name: Campaigns
          active: true
          count: unlimited
        - 
          name: Tours
          active: true
          count: unlimited
        - 
          name: UserAutoMessages
          active: true
          count: unlimited
        - 
          name: OutgoingWebhooks
          active: true
          count: unlimited
        - 
          name: OauthApplications
          active: true
          count: unlimited
        - 
          name: Articles
          active: true
          count: unlimited
        - 
          name: QuickReplies
          active: true
          count: unlimited
        - 
          name: CustomAttributes
          active: true
          count: unlimited